### ISSUE TITLE
PSD computation

### ISSUE THREAD

**Issue by Lukman-abdn19** [iris-edu/noise-toolkit#1]
HI,

I am using noise toolkit to compute PSDs, it was possible for me to produce hourly and daily PSD plots using window length = 3600s and 86400s respectively in the parameter file. But when I tried the same method to generate monthly plot, it didn't work. I would be very happy and thankful to get workable suggestions on how to compute monthly PSDs and a summarised general plot, thank you

**Comment by manoch-iris** [comment]
Hi, There should not be an issue with the monthly plots. Please sent me your parameter file and the command line you are using. Thanks!

**Comment by Lukman-abdn19** [comment]
Thank you for responding,

1. [computePSD.py.zip](https://github.com/iris-edu/noise-toolkit/files/6940709/computePSD.py.zip)

2. Terminal.
![Shell com](https://user-images.githubusercontent.com/62506325/128399453-3b51790e-49b7-4e51-a379-52c8de542914.jpeg)

When I used window length=86400s, I was able to compute PSD for a Month but the the PSD displayed is daily until you close the plot for the last day. Thank you

**Comment by manoch-iris** [comment]
Thank you for the information. Would you please tell me what you want to achieve because the parameters do not look right. Thanks

**Comment by Lukman-abdn19** [comment]
First, I want to generate PSD for a month, displayed on single plot. Then another plot to show the general PSD for 18 months. Thank you

**Comment by manoch-iris** [comment]
OK, you need to change your parameter file to what it was. The windowLength you changed in the parameter file is for computation of PSDs and usually hourly will work best. Making window length too long will reduce resolution. You compute these hourly PSDs for the duration you want and then use these to create your own plots etc. Take a look at https://github.com/iris-edu/noise-toolkit/wiki/Noise-Toolkit-PDF-PSD-package-V.2 and https://pubs.usgs.gov/of/2010/1292/pdf/OF10-1292.pdf for various examples (Noise Toolkit outputs follow the same general format of PQLX). You need to write your own code to do additional processing and plotting using the  PSDs repository that Noise toolkit generates.
