### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by tonino0013** [iris-edu/noise-toolkit#2]
Dear All,
I started to use the noise-toolkit to compute polarization, while working downloading from IRIS ok, however we have some offline data and we would like to apply your tool in our off-line data.

1 hour and 24 hour long data are located at:
D:\Inves\ML\noise-toolkit-master\data\MSEED\ 

My first question is related to param configuration file on computePolarization.py:

```
requestClient = "FILES"
fromFileOnly = True
fileTag = os.path.join(r'D:\Inves\ML\noise-toolkit-master\data\MSEED\' , "mseed", "*.mseed")
```

Is it ok?

Another question is related to my XML response files, I have separated files for each channel, however I saw over the examples that  in just one XML you managed the three channels, to fulfill this requirement I am using the [http://service.iris.edu/fdsnws/station/1/query?sta=SOEV&startafter=2020-06-01&endbefore=2020-06-02&minlatitude=-20&maxlatitude=-9&minlongitude=-70&maxlongitude=-63&level=channel] page  to 'merge' all channel in one XML, is it ok?

Thanks in advance. 
 
Tonino

**Comment by manoch-iris** [comment]
Dear Tonino,


> 1 hour and 24 hour long data are located at:
> D:\Inves\ML\noise-toolkit-master\data\MSEED\
> 
> My first question is related to param configuration file on computePolarization.py:
> 
> requestClient = "FILES"
> fromFileOnly = True
> fileTag = os.path.join(r'D:\Inves\ML\noise-toolkit-master\data\MSEED\' , "mseed", "*.mseed”)
> Is it ok?
> 
There appears to be and extra messed directory in your definition.

Assuming that your data path is D:\Inves\ML\noise-toolkit-master\data\MSEED\*.mseed, then you should use either:
fileTag = os.path.join(r'D:\Inves\ML\noise-toolkit-master\data\MSEED’,  '*.mseed')
or
fileTag = os.path.join(r'D:\Inves\ML\noise-toolkit-master\data’, ‘MSEED’, '*.mseed')

> Another question is related to my XML response files, I have separated files for each channel, however I saw over the examples that in just one XML you managed the three channels, to fulfill this requirement I am using the [http://service.iris.edu/fdsnws/station/1/query?sta=SOEV&startafter=2020-06-01&endbefore=2020-06-02&minlatitude=-20&maxlatitude=-9&minlongitude=-70&maxlongitude=-63&level=channel] page to 'merge' all channel in one XML, is it ok?
> 
Having one XML file is not a requirement. The code should scan your response directory and flag all the related response files and go through them to extract the response info. The service URL you used does not provide the response information you need. It only gives you the channel information. If you want to use that, change level from channel to response:
https://service.iris.edu/fdsnws/station/1/query?sta=SOEV&startafter=2020-06-01&endbefore=2020-06-02&minlatitude=-20&maxlatitude=-9&minlongitude=-70&maxlongitude=-63&level=response <https://service.iris.edu/fdsnws/station/1/query?sta=SOEV&startafter=2020-06-01&endbefore=2020-06-02&minlatitude=-20&maxlatitude=-9&minlongitude=-70&maxlongitude=-63&level=response>


Best,

—manoch,

**Comment by tonino0013** [comment]
Dear @manoch-iris,
Thank you  a lot for the answers, I will do what you told me.
Stay safe and best regards
Tonino

**Comment by tonino0013** [comment]
Dear @manoch-iris,
It worked fine, an example of my plot attach.
![Polarizarion_1day_SOEP_y](https://user-images.githubusercontent.com/9260897/132589368-3e9b014a-f86c-49ce-a09a-522904830e4f.png)

I just run the plotBinPolar.py script and I got the output D125.bin file, how can I plot it?
Thanks in advance.

**Comment by manoch-iris** [comment]
Dear Tonino

Glad to hear that it worked. Noise Toolkit is not a plotting package and all the plots it provides are for initial visualization. We do not have any plotting packages for the output data. It is up to you how to use and plot the data.


Best,

—manoch

**Comment by tonino0013** [comment]
Dear @manoch-iris ,
Thanks for the answers!!, stay safe and best regards
