### ISSUE TITLE
"fileTag" command line argument for NTK

### ISSUE THREAD

**Issue by acr34** [iris-edu/noise-toolkit#3]
My data is split into multiple (daily) directories in the noise_toolkit/data directory, and when I want to run the scripts for a new day I need to manually change the param file.
Could a command line argument be added to change the filetag directory and filename to point to the preferred file location? This way I may be able to automate the process as well.

**Comment by manoch-iris** [comment]
Hello @acr34! Although I understand your issue but customizing the code for every possible situation will make it unmanageable. That is one of the main reasons why we have released the code. You should be able to implement what you are requesting by following the same logic that we have used to override the default values in the parameter file. You could also achieve your objective via a wrapper script that would create symbolic links for directories as it goes through the days.  Best, --manoch
